"""Updated plans table

Revision ID: 0003
Revises: 0002
Create Date: 2023-09-27 15:49:58.591141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('plan', sa.Column('status', sa.String(), nullable=True))
    # op.add_column('plan', sa.Column('amount', sa.Numeric(), nullable=True))
    op.add_column('plan', sa.Column('reference_plan_id', sa.String(), nullable=True))
    op.create_unique_constraint('uk_plan_reference_id', 'plan', ['reference_plan_id'])
    # op.drop_column('plan', 'yearly_price')
    # op.drop_column('plan', 'monthly_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('plan', sa.Column('monthly_price', sa.NUMERIC(), autoincrement=False, nullable=False))
    # op.add_column('plan', sa.Column('yearly_price', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('plan', 'reference_plan_id')
    op.drop_constraint('uk_plan_reference_id', 'plan', type_='unique')
    # op.drop_column('plan', 'description')
    # op.drop_column('plan', 'amount')
    # op.drop_column('plan', 'status')
    # ### end Alembic commands ###
