"""Removed unique constraint from mobile_number in users table

Revision ID: 0005
Revises: 0004
Create Date: 2023-10-03 12:05:08.020017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plan', 'status',
            existing_type=sa.VARCHAR(),
            nullable=False)
    op.drop_constraint('user_mobile_number_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_mobile_number_key', 'user', ['mobile_number'])
    op.alter_column('plan', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
