"""Added reference_id _in_subscription_and_account_table

Revision ID: 0009
Revises: 0008
Create Date: 2023-10-07 16:18:03.304430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('reference_customer_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'account', ['reference_customer_id'])
    op.add_column('subscription', sa.Column('reference_subscription_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'subscription', ['reference_subscription_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription', type_='unique')
    op.drop_column('subscription', 'reference_subscription_id')
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_column('account', 'reference_customer_id')
    # ### end Alembic commands ###
