"""Mobile number nullable True

Revision ID: 0013
Revises: 0012
Create Date: 2023-10-10 19:05:09.423009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0013'
down_revision = '0012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'mobile_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'mobile_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
