"""removed_user_uuid_column_from_subscription_table

Revision ID: 0015
Revises: 0014
Create Date: 2023-10-12 10:43:39.259962

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0015'
down_revision = '0014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subscription_user_uuid_fkey', 'subscription', type_='foreignkey')
    op.drop_column('subscription', 'user_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('user_uuid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('subscription_user_uuid_fkey', 'subscription', 'user', ['user_uuid'], ['uuid'])
    # ### end Alembic commands ###
