"""added_unique_constraint_for_email_account_uuid_on_user_invite_table

Revision ID: 0017
Revises: 0016
Create Date: 2023-10-12 22:46:09.327632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0017'
down_revision = '0016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_invite', ['account_uuid', 'email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_invite', type_='unique')
    # ### end Alembic commands ###
