"""contract_module

Revision ID: 0018
Revises: 0017
Create Date: 2023-10-18 10:38:14.577459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0018'
down_revision = '0017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('account_uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_uuid'], ['account.uuid'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('contract',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('account_uuid', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('client_uuid', sa.String(), nullable=False),
    sa.Column('template_uuid', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_uuid'], ['account.uuid'], ),
    sa.ForeignKeyConstraint(['client_uuid'], ['client.uuid'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['template_uuid'], ['template.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('contract_signee',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('contract_uuid', sa.String(), nullable=False),
    sa.Column('signee_uuid', sa.String(), nullable=False),
    sa.Column('signee_email', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('signee_priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_uuid'], ['contract.uuid'], ),
    sa.ForeignKeyConstraint(['signee_uuid'], ['signee.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract_signee')
    op.drop_table('contract')
    op.drop_table('template')
    # ### end Alembic commands ###
