"""added_signee_fullname_and_signee_signature_in_signee_table

Revision ID: 0023
Revises: 0022
Create Date: 2023-10-25 12:28:46.211265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0023'
down_revision = '0022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_signee', sa.Column('signee_full_name', sa.String(), nullable=True))
    op.add_column('contract_signee', sa.Column('signee_signature', sa.Text(), nullable=True))
    # ### end Alembic commands ###
    op.execute("""
        UPDATE contract_signee
        SET signee_full_name = signee.full_name
        FROM signee
        WHERE contract_signee.signee_uuid = signee.uuid
    """)

    op.alter_column('contract_signee', 'signee_full_name',
            existing_type=sa.VARCHAR(),
            nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_signee', 'signee_signature')
    op.drop_column('contract_signee', 'signee_full_name')
    # ### end Alembic commands ###
