"""signed content in contract

Revision ID: 0024
Revises: 0023
Create Date: 2023-10-27 16:55:55.287266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0024'
down_revision = '0023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('signed_content', sa.Text(), nullable=True))

    op.execute("""
        UPDATE contract
        SET signed_content = content
    """)

    op.alter_column('contract', 'signed_content',
                    existing_type=sa.Text(),
                    nullable=False)
    ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'signed_content')
    # ### end Alembic commands ###
