"""signee_ip added in ContractSignee

Revision ID: 0025
Revises: 0024
Create Date: 2023-10-27 17:46:52.175678

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0025'
down_revision = '0024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_signee', sa.Column('signee_ip', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_signee', 'signee_ip')
    # ### end Alembic commands ###
