"""signed_at field added in ContractSignee Table

Revision ID: 0026
Revises: 0025
Create Date: 2023-10-31 17:38:09.902780

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0026'
down_revision = '0025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_signee', sa.Column('signed_at', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_signee', 'signed_at')
    # ### end Alembic commands ###
