"""made_duration_and_amount_fields_nullable

Revision ID: 0028
Revises: 0027
Create Date: 2023-11-06 19:36:23.402591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0028'
down_revision = '0027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contract', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('contract', 'amount',
               existing_type=sa.FLOAT(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contract', 'amount',
               existing_type=sa.FLOAT(precision=53),
               nullable=False)
    op.alter_column('contract', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
