"""added_folder_uuid_in_contract_table

Revision ID: 0030
Revises: 0029
Create Date: 2023-11-03 17:44:10.159458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from app.models.account import Account
from app.models.folder import Folder
from app.models.contract import Contract

# revision identifiers, used by Alembic.
revision = '0030'
down_revision = '0029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('contract', sa.Column('folder_uuid', sa.String(), nullable=True))
    # op.create_foreign_key(None, 'contract', 'folder', ['folder_uuid'], ['uuid'])
    # # Create a new session
    # bind = op.get_bind()
    # session = Session(bind=bind)
    #
    # # Retrieve all accounts
    # accounts = session.query(Account).all()
    #
    # for account in accounts:
    #     # Create a new folder for each account
    #     new_folder = Folder(
    #         uuid= Folder.create_uuid(),
    #         account_uuid = account.uuid,
    #         folder_name = 'Default',
    #         folder_name_slug = 'default'
    #     )
    #
    #     folder = session.add(new_folder)
    #     # Retrieve all contracts for the account and assign them to the folder
    #     contracts = session.query(Contract).filter_by(account_uuid=account.uuid).all()
    #     if contracts:
    #         for contract in contracts:
    #             contract.folder_uuid = new_folder.uuid
    #
    # # Commit the changes
    # session.commit()

    op.alter_column('contract', 'folder_uuid',
                    existing_type=sa.String(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contract', type_='foreignkey')
    op.drop_column('contract', 'folder_uuid')
    # ### end Alembic commands ###
