"""account_uuid added in contract_signee table

Revision ID: 0032
Revises: 0031
Create Date: 2023-11-09 12:47:45.026080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0032'
down_revision = '0031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_signee', sa.Column('account_uuid', sa.String(), nullable=True))
    op.create_foreign_key(None, 'contract_signee', 'account', ['account_uuid'], ['uuid'])
    op.execute("""
        UPDATE contract_signee
        SET account_uuid = contract.account_uuid
        FROM contract
        WHERE contract_signee.contract_uuid = contract.uuid;
    """)

    op.alter_column('contract_signee', 'account_uuid',
                    existing_type=sa.String(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contract_signee', type_='foreignkey')
    op.drop_column('contract_signee', 'account_uuid')
    # ### end Alembic commands ###
