"""added_deletion_scheduled_at_column_in_accounts_table

Revision ID: 0034
Revises: 0033
Create Date: 2023-11-16 17:09:42.103547

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0034'
down_revision = '0033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('deletion_scheduled_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'deletion_scheduled_at')
    # ### end Alembic commands ###
