"""added_cascade_in_all_models

Revision ID: 0035
Revises: 0034
Create Date: 2023-11-17 10:47:17.486237

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '0035'
down_revision = '0034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('branding_account_uuid_fkey', 'branding', type_='foreignkey')
    op.create_foreign_key('branding_account_uuid_fkey', 'branding', 'account', ['account_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('client_account_uuid_fkey', 'client', type_='foreignkey')
    op.create_foreign_key('client_account_uuid_fkey', 'client', 'account', ['account_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('contract_account_uuid_fkey', 'contract', type_='foreignkey')
    op.create_foreign_key('contract_account_uuid_fkey', 'contract', 'account', ['account_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('contract_log_account_uuid_fkey', 'contract_log', type_='foreignkey')
    op.create_foreign_key('contract_log_account_uuid_fkey', 'contract_log', 'account', ['account_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('contract_signee_account_uuid_fkey', 'contract_signee', type_='foreignkey')
    op.create_foreign_key('contract_signee_account_uuid_fkey', 'contract_signee', 'account', ['account_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('folder_account_uuid_fkey', 'folder', type_='foreignkey')
    op.create_foreign_key('folder_account_uuid_fkey', 'folder', 'account', ['account_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('payment_account_uuid_fkey', 'payment', type_='foreignkey')
    op.create_foreign_key('payment_account_uuid_fkey', 'payment', 'account', ['account_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('signee_account_uuid_fkey', 'signee', type_='foreignkey')
    op.create_foreign_key('signee_account_uuid_fkey', 'signee', 'account', ['account_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('subscription_account_uuid_fkey', 'subscription', type_='foreignkey')
    op.create_foreign_key('subscription_account_uuid_fkey', 'subscription', 'account', ['account_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('template_account_uuid_fkey', 'template', type_='foreignkey')
    op.create_foreign_key('template_account_uuid_fkey', 'template', 'account', ['account_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('user_account_uuid_fkey', 'user', type_='foreignkey')
    op.create_foreign_key('user_account_uuid_fkey', 'user', 'account', ['account_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('user_invite_account_uuid_fkey', 'user_invite', type_='foreignkey')
    op.create_foreign_key('user_invite_account_uuid_fkey', 'user_invite', 'account', ['account_uuid'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_invite_account_uuid_fkey', 'user_invite', type_='foreignkey')
    op.create_foreign_key('user_invite_account_uuid_fkey', 'user_invite', 'account', ['account_uuid'], ['uuid'])
    op.drop_constraint('user_account_uuid_fkey', 'user', type_='foreignkey')
    op.create_foreign_key('user_account_uuid_fkey', 'user', 'account', ['account_uuid'], ['uuid'])
    op.drop_constraint('template_account_uuid_fkey', 'template', type_='foreignkey')
    op.create_foreign_key('template_account_uuid_fkey', 'template', 'account', ['account_uuid'], ['uuid'])
    op.drop_constraint('subscription_account_uuid_fkey', 'subscription', type_='foreignkey')
    op.create_foreign_key('subscription_account_uuid_fkey', 'subscription', 'account', ['account_uuid'], ['uuid'])
    op.drop_constraint('signee_account_uuid_fkey', 'signee', type_='foreignkey')
    op.create_foreign_key('signee_account_uuid_fkey', 'signee', 'account', ['account_uuid'], ['uuid'])
    op.drop_constraint('payment_account_uuid_fkey', 'payment', type_='foreignkey')
    op.create_foreign_key('payment_account_uuid_fkey', 'payment', 'account', ['account_uuid'], ['uuid'])
    op.drop_constraint('folder_account_uuid_fkey', 'folder', type_='foreignkey')
    op.create_foreign_key('folder_account_uuid_fkey', 'folder', 'account', ['account_uuid'], ['uuid'])
    op.drop_constraint('contract_signee_account_uuid_fkey', 'contract_signee', type_='foreignkey')
    op.create_foreign_key('contract_signee_account_uuid_fkey', 'contract_signee', 'account', ['account_uuid'], ['uuid'])
    op.drop_constraint('contract_log_account_uuid_fkey', 'contract_log', type_='foreignkey')
    op.create_foreign_key('contract_log_account_uuid_fkey', 'contract_log', 'account', ['account_uuid'], ['uuid'])
    op.drop_constraint('contract_account_uuid_fkey', 'contract', type_='foreignkey')
    op.create_foreign_key('contract_account_uuid_fkey', 'contract', 'account', ['account_uuid'], ['uuid'])
    op.drop_constraint('client_account_uuid_fkey', 'client', type_='foreignkey')
    op.create_foreign_key('client_account_uuid_fkey', 'client', 'account', ['account_uuid'], ['uuid'])
    op.drop_constraint('branding_account_uuid_fkey', 'branding', type_='foreignkey')
    op.create_foreign_key('branding_account_uuid_fkey', 'branding', 'account', ['account_uuid'], ['uuid'])
    # ### end Alembic commands ###
