"""updated subscription status from free trial to active subscription

Revision ID: 0036
Revises: 0035
Create Date: 2023-11-20 17:49:17.486237

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '0036'
down_revision = '0035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.execute("UPDATE subscription SET status = 'active' WHERE status = 'free_trial'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE subscription SET status = 'free_trial' WHERE status = 'active'")
    # ### end Alembic commands ###
