"""unique constraint removed on email

Revision ID: 0037
Revises: 0036
Create Date: 2023-11-20 19:11:30.748764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0037'
down_revision = '0036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('signee_email_key', 'signee', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('signee_email_key', 'signee', ['email'])
    # ### end Alembic commands ###
