"""updated_email_template_body

Revision ID: 0038
Revises: 0037
Create Date: 2023-11-15 12:51:25.951084

"""
from alembic import op
from sqlalchemy.orm import Session
from app.models.account import Account
from app import logger
from app.helpers.constants import SEND_CONTRACT_TO_SIGNEE_EMAIL_TEMPLATE, SEND_REMINDER_TO_SIGNEE

# revision identifiers, used by Alembic.
revision = '0038'
down_revision = '0037'
branch_labels = None
depends_on = None


def upgrade():
    # Create a new session
    pass
    # bind = op.get_bind()
    # session = Session(bind=bind)
    #
    # try:
    #     # Retrieve all accounts
    #     accounts = session.query(Account).all()
    #
    #     for account in accounts:
    #         # Update predefined templates
    #         op.execute("""
    #             UPDATE email_template
    #             SET email_body = :template_value
    #             WHERE email_type = 'SEND_CONTRACT_TO_SIGNEE'
    #         """, {'template_value': SEND_CONTRACT_TO_SIGNEE_EMAIL_TEMPLATE})
    #
    #         op.execute("""
    #             UPDATE email_template
    #             SET email_body = :template_value
    #             WHERE email_type = SEND_REMINDER_TO_SIGNEE
    #         """, {'template_value': SEND_REMINDER_TO_SIGNEE})
    #
    #     # Commit changes
    #     session.commit()
    #
    # except Exception as e:
    #     logger.info(f'Error during upgrade: {e}')
    #     session.rollback()
    # finally:
    #     session.close()



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
