"""updated_contact_us_fields_to_be_optional

Revision ID: 0040
Revises: 0039
Create Date: 2023-11-22 17:43:20.957391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0040'
down_revision = '0039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact_us', 'first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('contact_us', 'last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('contact_us', 'company_size',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('contact_us', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact_us', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('contact_us', 'company_size',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('contact_us', 'last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('contact_us', 'first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
