"""client_uuid in contract signee table

Revision ID: 0041
Revises: 0040
Create Date: 2023-11-21 16:52:53.943257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0041'
down_revision = '0040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_signee', sa.Column('client_uuid', sa.String(), nullable=True))
    op.create_foreign_key(None, 'contract_signee', 'client', ['client_uuid'], ['uuid'])
    op.execute("""
         UPDATE contract_signee
         SET client_uuid = contract.client_uuid
         FROM contract
         WHERE contract_signee.contract_uuid = contract.uuid;
    """)
    op.alter_column('contract_signee', 'client_uuid',
                    existing_type=sa.String(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contract_signee_client_uuid_fkey', 'contract_signee', type_='foreignkey')
    op.drop_column('contract_signee', 'client_uuid')
    # ### end Alembic commands ###
