"""new fields added in contract signee

Revision ID: 0042
Revises: 0041
Create Date: 2023-11-21 17:01:39.931596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0042'
down_revision = '0041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('is_account_client', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('contract_signee', sa.Column('is_account_signee', sa.Boolean(), server_default='f', nullable=False))
    op.alter_column('contract_signee', 'signee_priority',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('signee', 'signing_sequence',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signee', 'signing_sequence',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('contract_signee', 'signee_priority',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('contract_signee', 'is_account_signee')
    op.drop_column('client', 'is_account_client')
    # ### end Alembic commands ###
