"""currency_code added in account and contract

Revision ID: 0044
Revises: 0043
Create Date: 2023-11-27 19:36:15.999686

"""
from alembic import op
import sqlalchemy as sa

from app.helpers.constants import CurrencyCode
from app.models.account import Account
from app.models.client import Client
from app.models.contract import Contract

# revision identifiers, used by Alembic.
revision = '0044'
down_revision = '0043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('currency_code', sa.String(length=3), nullable=True))
    op.add_column('contract', sa.Column('currency_code', sa.String(length=3), nullable=True))
    # all_account = Account.get_all()
    # for account_obj in all_account:
    #     account_country = account_obj.country
    #     if account_country:
    #         account_obj.currency_code = CurrencyCode.get(account_country, None)
    #         Account.update()
    # all_contracts = Contract.get_all()
    # for contract_obj in all_contracts:
    #     client_uuid = contract_obj.client_uuid
    #     client_obj = Client.get_by_uuid(uuid=client_uuid)
    #     client_country = client_obj.country
    #     if client_country:
    #         contract_obj.currency_code = CurrencyCode.get(client_country, None)
    #         Contract.update()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'currency_code')
    op.drop_column('account', 'currency_code')
    # ### end Alembic commands ###
