"""vat_percentage in contract table

Revision ID: 0045
Revises: 0044
Create Date: 2023-11-24 13:25:01.072185

"""
from alembic import op
import sqlalchemy as sa

from app.models.account import Account
from app.models.client import Client
from app.models.contract import Contract

# revision identifiers, used by Alembic.
revision = '0045'
down_revision = '0044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('vat_percentage', sa.Float(), nullable=True))
    # all_contracts = Contract.get_all()
    # for contract_obj in all_contracts:
    #     client_uuid = contract_obj.client_uuid
    #     account_uuid = contract_obj.account_uuid
    #
    #     client_obj = Client.get_by_uuid(uuid=client_uuid)
    #     account_obj = Account.get_by_uuid(uuid=account_uuid)
    #
    #     account_country = account_obj.country
    #     client_country = client_obj.country
    #
    #     if account_country == client_country:
    #         contract_obj.vat_percentage = float(account_obj.vat_percentage)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'vat_percentage')
    # ### end Alembic commands ###
