# PostgresSQL

ADMIN:
  NAME: ""
  FIRST_NAME: ""
  LAST_NAME: ""
  PRIMARY_EMAIL: ""
  MOBILE_NUMBER: ""
  PASSWORD: ""

ADMIN_NOTIFICATION_EMAIL: ""

APP_ENV: "DEV"
APP_URL: ""
POSTGRES_USER: "root_user"
POSTGRES_PW: "XgKx7DQ2dUmYcL56"
POSTGRES_URL: "127.0.0.1:5432"
POSTGRES_DB: "boiler_plate"

COGNITO_APP_CLIENT_ID:
COGNITO_REGION:
COGNITO_USER_POOL_ID:
COGNITO_USER_CLIENT_SECRET:
COGNITO_IDP_CALLBACK_URL:
COGNITO_DOMAIN_URL:

GOOGLE_INFO_URL: "https://www.googleapis.com/oauth2/v1/userinfo"

GPT_MODEL_3_TURBO: "gpt-3.5-turbo"
GPT_MODEL_4: "gpt-4"
OPEN_AI_KEY: ""
AWS_KEY: ""
AWS_SECRET: ""

HASH_ID_SALT: "0987654321"
SECRET_KEY: "123412"
RQ_JOB_TIMEOUT: 100000

MAIL:
  MAIL_SERVER: "smtp.mailgun.org"
  MAIL_PORT: 465
  MAIL_USERNAME: "something@notifications.active.space"
  MAIL_PASSWORD: "966f"
  MAIL_USE_TLS: False
  MAIL_USE_SSL: True
  MAIL_DEFAULT_SENDER: "info@active.space"
  MAIL_DEFAULT_SENDER_NAME: "BoilerPlate"

OPEN_URLS:
  - "/api/v1/user/create"
  - "/api/v1/user/create-admin"
  - "/api/v1/user/authenticate"
  - "/api/v1/user/confirm-verification-code"
  - "/api/v1/user/resend-verification-code"
  - "/api/v1/plan/get-all-plans"
  - "/api/v1/subscription/create"
  - "/api/v1/contact-us/create"
  - "/api/v1/handle-webhook"
  - "/api/v1/user-invite/set-password"
  - "/api/v1/user-invite/accept"
  - "/api/v1/user/login-with-google"
  - "/api/v1/user/idp-callback"
  - "/api/v1/contract/verify-contract-token"
  - "/api/v1/contract/track-open"
  - "/api/v1/contract/submit"
  - "/api/v1/contract/get-signature-s3-link"

RATE_LIMIT: # Used by Flask-Limiter
  STRATEGY: "moving-window"
  KEY_PREFIX: "RATE_LIMITING"
  REDIS_DB: 1

REDIS: # Used to initialize redis objects
  HOST: "localhost"
  PORT: 6379
  DB: 0

S3_REGION: ""
S3_BUCKET: ""

SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://postgres:new_password@127.0.0.1:5432/boiler_plate"
SQLALCHEMY_TRACK_MODIFICATIONS: False
SQLALCHEMY_ENGINE_OPTIONS: { "isolation_level": "AUTOCOMMIT" }
CELERY_BROKER_URL: "pyamqp://lims_root_rabbitmq:Ey6ftnhsdyRL6Lpg@localhost:5672/lims_rabbitmq"
LOG_FILE_PATH: "/opt/edugem/apps/virtusign-backend/logs/app.log"

SQLALCHEMY_TEST_DATABASE_URI: "postgresql+psycopg2://postgres:new_password@127.0.0.1:5432/flask_boiler_test"
TESTING: False

STRIPE_SECRET_KEY: ""
STRIPE_PUBLISHABLE_KEY: ""
STRIPE_WEBHOOK_SECRET: ""

SUPER_ADMIN_TOKEN: ""

TEST_USER:
  FIRST_NAME:
  EMAIL:
  MOBILE_NUMBER:
  PASSWORD:
  POSTAL_CODE:
  CITY:
  REGION:
  COUNTRY:
  SIGNATURE:
  VAT_PERCENTAGE:

TEST_USER_TOKEN: ""
