name: Release Please testing
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        #  if: github.ref == 'refs/heads/dev'

      - uses: actions/setup-python@v3
        #  if: github.ref == 'refs/heads/dev'
        with:
          python-version: 3.8

      - name: Install dependencies
        #  if: github.ref == 'refs/heads/dev'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # replace with your dependencies
          pip install pytest
          pre-commit install --hook-type commit-msg

      - uses: pre-commit/action@v3.0.0
        #  if: github.ref == 'refs/heads/dev'


  # spell-check:
  #   name: spell check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: check-spelling
  #       id: spelling
  #       uses: check-spelling/check-spelling@main
  #       with:
  #         check_file_names: 1
  #         extra_dictionaries:
  #           cspell:aws/aws.txt
  #           cspell:software-terms/dict/softwareTerms.txt
  #           cspell:npm/dict/npm.txt
  #           cspell:typescript/dict/typescript.txt
  #           cspell:node/dict/node.txt

  # - uses: rojopolis/spellcheck-github-actions@0.35.0
  #   name: Spellcheck
  #   with:
  #     config: ./spellcheck.yaml

